TelaManager:

    TelaLogin:
    TelaInicial:
    TelaFuncionarios:
    TelaRelatorios:
    TelaFinanceiro:
    TelaConfiguracoes:

<DrawerClickableItem@MDNavigationDrawerItem>
    focus_color: "#adc5f0"
    text_color: "#4a4939"
    icon_color: "#4a4939"
    ripple_color: "#c5bdd2"



<TelaLogin>:
    name: 'TelaLogin'
    id: 'Login'
    MDFloatLayout:
        MDIconButton:
            icon: 'account-circle'
            pos_hint: {'center_x': .5, 'center_y': .75}
            icon_size: '78sp'
        MDTextField:
            id: text_email
            hint_text: 'Email'
            size_hint: .7, .13
            pos_hint: {'center_x': .5, 'center_y': .6}
        MDTextField:
            id: text_senha
            hint_text: 'Senha'
            size_hint: .7, .13
            pos_hint: {'center_x': .5, 'center_y': .5}
            password: True
        MDIconButton:
            icon: "eye-off"
            pos_hint: {"center_y": .5}
            pos_hint: {'center_x': .8, 'center_y': .5}
            theme_text_color: "Hint"
            on_release:
                self.icon = "eye" if self.icon == "eye-off" else "eye-off"
                text_senha.password = False if text_senha.password is True else True
        MDRaisedButton:
            text: 'Login'
            text_color: 'black'
            size_hint: .7, .05
            pos_hint:{'center_x': .5, 'center_y': .4}
            on_release: if root.login(): app.root.current = 'TelaInicial'
        MDTextButton:
            text: 'Recuperar senha'
            pos_hint:{'center_x': .5, 'center_y': .33}
            on_release: root.AbrirRecSenha()


<EsqueciSenha>
    orientation: 'vertical'
    size_hint: .75, .5
    pos_hint:{'center_x': .5, 'center_y': .4}

    MDBoxLayout:
        size_hint_y: .2
        padding: [25,0,25,0]
        md_bg_color: app.theme_cls.primary_color

        MDLabel:
            text:'Atualizar senha'
            theme_text_color: 'Custom'
            text_color: 1,1,1,1

        MDIconButton:
            icon: 'close'
            theme_text_color: 'Custom'
            text_color: 1,1,1,1
            on_release: root.FecharRecSenha()


    MDFloatLayout:

        MDTextField:
            pos_hint:{'center_x': .5, 'center_y': .75}
            size_hint_x: .9
            hint_text: 'Código enviado para o email'
        MDTextField:
            pos_hint:{'center_x': .5, 'center_y': .55}
            size_hint_x: .9
            hint_text: 'Nova senha'
        MDTextField:
            pos_hint:{'center_x': .5, 'center_y': .35}
            size_hint_x: .9
            hint_text: 'Confirmação'
        MDRaisedButton:
            pos_hint:{'center_x': .5, 'center_y': .1}
            size_hint_x: .9
            text: 'Recuperar'



<TelaInicial>:
    id: TelaInicial
    name: 'TelaInicial'
    MDFloatLayout:
        MDTopAppBar:
            pos_hint:{'center_x': .5, 'center_y': .95}
            left_action_items: [['menu', lambda x: nav_drawer.set_state("open")]]
            right_action_items: [['account', lambda x: root.login_config()]]
        MDLabel:
            text: 'Buscar Funcionário'
            pos_hint:{'center_x': .55, 'center_y': .8}
        MDTextField:
            hint_text: 'Nome/CPF'
            mode: 'rectangle'
            pos_hint:{'center_x': .5, 'center_y': .73}
            size_hint_x: .9
            size_hint_Y: .3

        MDNavigationLayout:


            MDScreenManager:
                id: screen_manager
            MDNavigationDrawer:
                id: nav_drawer
                radius: (0, 16, 16, 0)

                ContentNavigationDrawer:
                    screen_manager: screen_manager
                    nav_drawer: nav_drawer




<ContentNavigationDrawer>:
    MDNavigationDrawerMenu:
        MDNavigationDrawerHeader:
            title: 'FL'
        DrawerClickableItem:
            text: "Funcionários"
            icon: 'account-search-outline'
            on_release:
                root.nav_drawer.set_state("close")
                app.root.current = 'Funcionarios'
        DrawerClickableItem:
            icon: 'finance'
            text: "Relatórios"
            on_release:
                root.nav_drawer.set_state("close")
                app.root.current = 'Relatorios'
        DrawerClickableItem:
            icon: 'currency-usd'
            text: "Financeiro"
            on_release:
                root.nav_drawer.set_state("close")
                app.root.current = 'Financeiro'
        DrawerClickableItem:
            icon: 'cog-outline'
            text: "Configurações"
            on_release:
                root.nav_drawer.set_state("close")
                app.root.current = 'Configuracoes'


<TelaFuncionarios>
    name: 'Funcionarios'
    MDFloatLayout:
        MDTopAppBar:
            pos_hint:{'center_x': .5, 'center_y': .95}
            left_action_items: [['menu', lambda x: nav_drawer.set_state("open")]]
            right_action_items: [['account', lambda x: root.login_config()]]
        MDLabel:
            text: "Tela Funcionarios"
            halign: "center"
        MDNavigationLayout:

            MDScreenManager:
                id: screen_manager
            MDNavigationDrawer:
                id: nav_drawer
                radius: (0, 16, 16, 0)

                ContentNavigationDrawer:
                    screen_manager: screen_manager
                    nav_drawer: nav_drawer

<TelaRelatorios>
    name: 'Relatorios'
    MDFloatLayout:
        MDTopAppBar:
            pos_hint:{'center_x': .5, 'center_y': .95}
            left_action_items: [['menu', lambda x: nav_drawer.set_state("open")]]
            right_action_items: [['account', lambda x: root.login_config()]]
        MDLabel:
            text: "Tela Relatórios"
            halign: "center"
        MDNavigationLayout:

            MDScreenManager:
                id: screen_manager
            MDNavigationDrawer:
                id: nav_drawer
                radius: (0, 16, 16, 0)

                ContentNavigationDrawer:
                    screen_manager: screen_manager
                    nav_drawer: nav_drawer


<TelaFinanceiro>
    name: 'Financeiro'
    MDFloatLayout:
        MDTopAppBar:
            pos_hint:{'center_x': .5, 'center_y': .95}
            left_action_items: [['menu', lambda x: nav_drawer.set_state("open")]]
            right_action_items: [['account', lambda x: root.login_config()]]
        MDLabel:
            text: "Tela Financeiro"
            halign: "center"
    MDNavigationLayout:

        MDScreenManager:
            id: screen_manager
        MDNavigationDrawer:
            id: nav_drawer
            radius: (0, 16, 16, 0)

            ContentNavigationDrawer:
                screen_manager: screen_manager
                nav_drawer: nav_drawer

<TelaConfiguracoes>
    name: 'Configuracoes'
    MDFloatLayout:
        MDTopAppBar:
            pos_hint:{'center_x': .5, 'center_y': .95}
            left_action_items: [['menu', lambda x: nav_drawer.set_state("open")]]
            right_action_items: [['account', lambda x: root.login_config()]]
        MDLabel:
            text: "Tela Configuração"
            halign: "center"
    MDNavigationLayout:

        MDScreenManager:
            id: screen_manager
        MDNavigationDrawer:
            id: nav_drawer
            radius: (0, 16, 16, 0)

            ContentNavigationDrawer:
                screen_manager: screen_manager
                nav_drawer: nav_drawer





















