Screen:
    TelaLogin:

<TelaLogin>:

    MDBoxLayout:
        md_bg_color: '#d2f2f7'
        orientation: 'vertical'
        MDTopAppBar:
            title: 'FP'
            left_action_items: [["finance", lambda x: x]]
            right_action_items: [["menu", lambda x: root.AbrirMenu()]]


        MDFloatLayout:
            MDIconButton:
                icon: 'account-circle'
                pos_hint: {'center_x': .5, 'center_y': .75}
                icon_size: '78sp'
            MDTextField:
                hint_text: 'Email'
                size_hint: .7, .13
                pos_hint: {'center_x': .5, 'center_y': .6}
            MDTextField:
                id: text_senha
                hint_text: 'Senha'
                size_hint: .7, .13
                pos_hint: {'center_x': .5, 'center_y': .5}
                password: True
            MDIconButton:
                icon: "eye-off"
                pos_hint: {"center_y": .5}
                pos_hint: {'center_x': .8, 'center_y': .5}
                theme_text_color: "Hint"
                on_release:
                    self.icon = "eye" if self.icon == "eye-off" else "eye-off"
                    text_senha.password = False if text_senha.password is True else True
            MDRaisedButton:
                text: 'Login'
                text_color: 'black'
                size_hint: .7, .05
                pos_hint:{'center_x': .5, 'center_y': .4}
                md_bg_color: "white"
            MDTextButton:
                text: 'Recuperar senha'
                pos_hint:{'center_x': .5, 'center_y': .33}
                on_release: root.AbrirRecSenha()

<MenuLogin>
    orientation: 'vertical'
    size_hint: .5, .5
    pos_hint:{'center_x': .75, 'center_y': .75}

<EsqueciSenha>
    orientation: 'vertical'
    size_hint: .75, .5
    pos_hint:{'center_x': .5, 'center_y': .4}

    MDBoxLayout:
        size_hint_y: .2
        padding: [25,0,25,0]
        md_bg_color: app.theme_cls.primary_color

        MDLabel:
            text:'Atualizar senha'
            theme_text_color: 'Custom'
            text_color: 1,1,1,1

        MDIconButton:
            icon: 'close'
            theme_text_color: 'Custom'
            text_color: 1,1,1,1
            on_release: root.FecharRecSenha()


    MDFloatLayout:

        MDTextField:
            pos_hint:{'center_x': .5, 'center_y': .75}
            size_hint_x: .9
            hint_text: 'Código enviado para o email'
        MDTextField:
            pos_hint:{'center_x': .5, 'center_y': .55}
            size_hint_x: .9
            hint_text: 'Nova senha'
        MDTextField:
            pos_hint:{'center_x': .5, 'center_y': .35}
            size_hint_x: .9
            hint_text: 'Confirmação'
        MDRaisedButton:
            pos_hint:{'center_x': .5, 'center_y': .1}
            size_hint_x: .9
            text: 'Recuperar'


<TelaIncial>:







